const eventsData = {
    'Cluj-Napoca': [
        // Evenimente pentru 16 Noiembrie 2025
        {
            id: 'evt1',
            title: 'Concert Rock in Centru',
            description: 'Concert live cu trupe locale de rock in centrul orasului.Concert live cu trupe locale de rock in centrul orasului. ',
            date: '2025-11-16',
            time: '19:00',
            location: 'Piata Unirii',
            address: 'Piata Unirii, Cluj-Napoca',
            price: '50 RON',
            category: 'Muzica',
            image: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?q=80&w=1000',
            lat: 46.7694,
            lng: 23.5900
        },
        {
            id: 'evt2',
            title: 'Filmul Sapte',
            description: 'Vizionare film thriller cu Brad Pitt si Morgan Freeman.',
            date: '2025-11-16',
            time: '21:00',
            location: 'Cinema City',
            address: 'Str. Dorobantilor 18, Cluj-Napoca',
            price: '35 RON',
            category: 'Film',
            image: 'https://cdn.pixabay.com/photo/2024/05/26/10/15/bird-8788491_1280.jpg',
            lat: 46.7710,
            lng: 23.5950
        },
        {
            id: 'evt3',
            title: 'Tur al Castelului Corvinilor',
            description: 'Excursie organizata la Castelul Corvinilor.',
            date: '2025-11-16',
            time: '08:00',
            location: 'Plecare din Piata Avram Iancu',
            address: 'Piata Avram Iancu, Cluj-Napoca',
            price: '120 RON',
            category: 'Film',
            image: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?q=80&w=1000',
            lat: 46.7700,
            lng: 23.5950
        },
        {
            id: 'evt4',
            title: 'Expozitie de Arta Contemporana',
            description: 'Lucrari ale artistilor contemporani din Romania.',
            date: '2025-11-16',
            time: '12:00',
            location: 'Muzeul de Arta Cluj',
            address: 'Piata Unirii 30, Cluj-Napoca',
            price: '25 RON',
            category: 'Arta',
            image: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?q=80&w=1000',
            lat: 46.7692,
            lng: 23.5915
        },
        {
            id: 'evt5',
            title: 'Gaming Night',
            description: 'Seara de jocuri video competitive cu premii.',
            date: '2025-11-16',
            time: '20:00',
            location: 'Gaming Hub Cluj',
            address: 'Str. Horea 15, Cluj-Napoca',
            price: '40 RON',
            category: 'Jocuri',
            image: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?q=80&w=1000',
            lat: 46.7680,
            lng: 23.5900
        },
        // Evenimente pentru 17 Noiembrie 2025
        {
            id: 'evt6',
            title: 'Targ de Antichitati',
            description: 'Obiecte vechi si antichitati la preturi mici.',
            date: '2025-11-17',
            time: '10:00',
            location: 'Piata Muzeului',
            address: 'Piata Muzeului, Cluj-Napoca',
            price: 'Intrare libera',
            category: 'Targ',
            image: 'https://cdn.pixabay.com/photo/2024/05/26/10/15/bird-8788491_1280.jpg',
            lat: 46.7689,
            lng: 23.5894
        },
        {
            id: 'evt7',
            title: 'Concert Jazz',
            description: 'Muzica jazz in aer liber cu artisti internationali.',
            date: '2025-11-17',
            time: '19:30',
            location: 'Gradina Botanica',
            address: 'Str. Republicii 42, Cluj-Napoca',
            price: '60 RON',
            category: 'Muzica',
            image: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?q=80&w=1000',
            lat: 46.7660,
            lng: 23.5830
        },
        {
            id: 'evt8',
            title: 'Workshop de Fotografie',
            description: 'Invatati tehnici avansate de fotografie.',
            date: '2025-11-17',
            time: '15:00',
            location: 'Centrul Cultural Clujean',
            address: 'Str. I.C. Bratianu 12, Cluj-Napoca',
            price: '80 RON',
            category: 'Workshop',
            image: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?q=80&w=1000',
            lat: 46.7710,
            lng: 23.5970
        },
        {
            id: 'evt9',
            title: 'Teatru: O Scrisoare Pierduta',
            description: 'Piesa clasica de I.L. Caragiale.',
            date: '2025-11-17',
            time: '18:30',
            location: 'Teatrul National Cluj',
            address: 'Piata Stefan cel Mare 2-4, Cluj-Napoca',
            price: '50-100 RON',
            category: 'Teatru',
            image: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?q=80&w=1000',
            lat: 46.7705,
            lng: 23.5950
        },
        {
            id: 'evt10',
            title: 'Stand-up Comedy Night',
            description: 'Seara de comedie cu cei mai buni comici din Romania.',
            date: '2025-11-17',
            time: '21:00',
            location: 'The Office Pub',
            address: 'Str. Memorandumului 9, Cluj-Napoca',
            price: '35 RON',
            category: 'Comedie',
            image: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?q=80&w=1000',
            lat: 46.7685,
            lng: 23.5940
        },
        // Evenimente pentru 18 Noiembrie 2025
        {
            id: 'evt11',
            title: 'Targ de Craciun',
            description: 'Inceputul targului de Craciun din centrul orasului.',
            date: '2025-11-18',
            time: '12:00',
            location: 'Piata Unirii',
            address: 'Piata Unirii, Cluj-Napoca',
            price: 'Intrare libera',
            category: 'Targ',
            image: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?q=80&w=1000',
            lat: 46.7694,
            lng: 23.5900
        },
        {
            id: 'evt12',
            title: 'Expozitie Auto',
            description: 'Cele mai noi modele de masini la expozitie.',
            date: '2025-11-18',
            time: '10:00',
            location: 'Sala Polivalenta',
            address: 'Str. Horea 7, Cluj-Napoca',
            price: '40 RON',
            category: 'Auto',
            image: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?q=80&w=1000',
            lat: 46.7670,
            lng: 23.5920
        },
        {
            id: 'evt13',
            title: 'Concert Muzica Clasica',
            description: 'Simfonii de Mozart si Beethoven.',
            date: '2025-11-18',
            time: '19:00',
            location: 'Filarmonica de Stat',
            address: 'Str. Kogalniceanu 11, Cluj-Napoca',
            price: '70-150 RON',
            category: 'Muzica',
            image: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?q=80&w=1000',
            lat: 46.7700,
            lng: 23.5980
        },
        {
            id: 'evt14',
            title: 'Film: Inception',
            description: 'Proiectie speciala a filmului Inception.',
            date: '2025-11-18',
            time: '20:30',
            location: 'Cinema Victoria',
            address: 'Piata Unirii, Cluj-Napoca',
            price: '30 RON',
            category: 'Film',
            image: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?q=80&w=1000',
            lat: 46.7750,
            lng: 23.5900
        },
        {
            id: 'evt15',
            title: 'Tur Ghetoului Evreiesc',
            description: 'Tur istoric prin vechiul cartier evreiesc.',
            date: '2025-11-18',
            time: '16:00',
            location: 'Piata Unirii',
            address: 'Piata Unirii, Cluj-Napoca',
            price: '25 RON',
            category: 'Turism',
            image: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?q=80&w=1000',
            lat: 46.7730,
            lng: 23.5900
        },
        // Evenimente pentru 19 Noiembrie 2025
        {
            id: 'evt16',
            title: 'Targ de Vechituri',
            description: 'Obiecte vechi si antichitati la preturi mici.Obiecte vechi si antichitati la preturi mici.Obiecte vechi si antichitati la preturi mici.',
            date: '2025-11-19',
            time: '09:00',
            location: 'Piata Marasti',
            address: 'Piata Marasti, Cluj-Napoca',
            price: 'Intrare libera',
            category: 'Muzica',
            image: 'https://cdn.pixabay.com/photo/2024/05/26/10/15/bird-8788491_1280.jpg',
            lat: 46.7780,
            lng: 23.6000
        },
        {
            id: 'evt17',
            title: 'Concert Rock Alternativ',
            description: 'Concert cu trupe locale de rock alternativ.',
            date: '2025-11-19',
            time: '20:00',
            location: 'Form Space',
            address: 'Str. Fabricii 12, Cluj-Napoca',
            price: '45 RON',
            category: 'Muzica',
            image: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?q=80&w=1000',
            lat: 46.7750,
            lng: 23.6100
        },
        {
            id: 'evt18',
            title: 'Workshop de Gatit',
            description: 'Invatati sa gatiti preparate traditionale romanesti.',
            date: '2025-11-19',
            time: '14:00',
            location: 'Scoala de Gatit Cluj',
            address: 'Str. Memorandumului 45, Cluj-Napoca',
            price: '120 RON',
            category: 'Film',
            image: 'https://cdn.pixabay.com/photo/2024/05/26/10/15/bird-8788491_1280.jpg',
            lat: 46.7690,
            lng: 23.5960
        },
        {
            id: 'evt19',
            title: 'The Dark Knight',
            description: 'Proiectie speciala a filmului The Dark Knight.',
            date: '2025-11-19',
            time: '21:00',
            location: 'Cinema City',
            address: 'Str. Dorobantilor 18, Cluj-Napoca',
            price: '30 RON',
            category: 'Film',
            image: 'https://cdn.pixabay.com/photo/2024/05/26/10/15/bird-8788491_1280.jpg',
            lat: 46.7710,
            lng: 23.5950
        },
        {
            id: 'evt20',
            title: 'Seara de Board Games',
            description: 'Jocuri de societate in aer liber.',
            date: '2025-11-19',
            time: '17:00',
            location: 'Parcul Central',
            address: 'Parcul Central, Cluj-Napoca',
            price: '20 RON',
            category: 'Jocuri',
            image: 'https://cdn.pixabay.com/photo/2024/05/26/10/15/bird-8788491_1280.jpg',
            lat: 46.7749,
            lng: 23.6067
        },
        // Evenimente pentru 19 Noiembrie 2025
        {
            id: 'evt21',
            title: 'Expozitie de Arta Moderna',
            description: 'Lucrari ale artistilor moderni din Romania.',
            date: '2025-11-19',
            time: '11:00',
            location: 'Muzeul de Arta Cluj',
            address: 'Piata Unirii 30, Cluj-Napoca',
            price: '25 RON',
            category: 'Arta',
            image: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?q=80&w=1000',
            lat: 46.7692,
            lng: 23.5915
        },
        {
            id: 'evt22',
            title: 'Concert Muzica Populara',
            description: 'Concert de muzica populara romaneasca.',
            date: '2025-11-19',
            time: '18:00',
            location: 'Sala Sporturilor Horia Demian',
            address: 'St. Taietura Turcului 1, Cluj-Napoca',
            price: '50-100 RON',
            category: 'Muzica',
            image: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?q=80&w=1000',
            lat: 46.7611,
            lng: 23.5935
        },
               {
            id: 'evt41',
            title: 'Concert Muzica Populara',
            description: 'Concert de muzica populara romaneasca.',
            date: '2025-11-19',
            time: '18:00',
            location: 'Sala Sporturilor Horia Demian',
            address: 'St. Taietura Turcului 1, Cluj-Napoca',
            price: '50-100 RON',
            category: 'Muzica',
            image: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?q=80&w=1000',
            lat: 46.7630,
            lng: 23.5935
        },
        {
            id: 'evt23',
            title: 'Tur al Cetatii Clujului',
            description: 'Tur istoric prin vechile ziduri ale cetatii.',
            date: '2025-11-19',
            time: '15:00',
            location: 'Piata Unirii',
            address: 'Piata Unirii, Cluj-Napoca',
            price: '30 RON',
            category: 'Turism',
            image: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?q=80&w=1000',
            lat: 46.7694,
            lng: 23.5900
        },
        {
            id: 'evt24',
            title: 'Workshop de Dans',
            description: 'Invatati dansuri populare romanesti.',
            date: '2025-11-19',
            time: '16:00',
            location: 'Centrul Cultural Clujean',
            address: 'Str. I.C. Bratianu 12, Cluj-Napoca',
            price: '40 RON',
            category: 'Dans',
            image: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?q=80&w=1000',
            lat: 46.7710,
            lng: 23.5970
        },
        {
            id: 'evt25',
            title: 'Film: Interstellar',
            description: 'Proiectie speciala a filmului Interstellar.',
            date: '2025-11-19',
            time: '20:00',
            location: 'Cinema Victoria',
            address: 'Piata Unirii, Cluj-Napoca',
            price: '35 RON',
            category: 'Film',
            image: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?q=80&w=1000',
            lat: 46.7694,
            lng: 23.5900
        },
        // Evenimente pentru 20 Noiembrie 2025
        {
            id: 'evt26',
            title: 'Targ de Carti Vechi',
            description: 'Carti vechi si de colectie la preturi mici.',
            date: '2025-11-20',
            time: '10:00',
            location: 'Piata Muzeului',
            address: 'Piata Muzeului, Cluj-Napoca',
            price: 'Intrare libera',
            category: 'Targ',
            image: 'https://example.com/old_books.jpg',
            lat: 46.7689,
            lng: 23.5894
        },
        {
            id: 'evt27',
            title: 'Concert Muzica Usoara',
            description: 'Seare de muzica usoara romaneasca.',
            date: '2025-11-20',
            time: '19:00',
            location: 'Sala Dalles',
            address: 'Str. Avram Iancu 15, Cluj-Napoca',
            price: '60 RON',
            category: 'Muzica',
            image: 'https://example.com/easy_listening.jpg',
            lat: 46.7705,
            lng: 23.5950
        },
        {
            id: 'evt28',
            title: 'Tur al Gradinii Botanice',
            description: 'Tur ghidat prin gradina botanica.',
            date: '2025-11-20',
            time: '11:00',
            location: 'Gradina Botanica',
            address: 'Str. Republicii 42, Cluj-Napoca',
            price: '20 RON',
            category: 'Turism',
            image: 'https://example.com/botanical_garden.jpg',
            lat: 46.7660,
            lng: 23.5830
        },
        {
            id: 'evt29',
            title: 'Workshop de Pictura',
            description: 'Invatati tehnici de pictura in ulei.',
            date: '2025-11-20',
            time: '14:00',
            location: 'Atelierul de Arta',
            address: 'Str. Horea 25, Cluj-Napoca',
            price: '90 RON',
            category: 'Arta',
            image: 'https://example.com/painting_workshop.jpg',
            lat: 46.7670,
            lng: 23.5910
        },
        {
            id: 'evt30',
            title: 'Film: The Shawshank Redemption',
            description: 'Proiectie speciala a filmului The Shawshank Redemption.',
            date: '2025-11-20',
            time: '20:30',
            location: 'Cinema City',
            address: 'Str. Dorobantilor 18, Cluj-Napoca',
            price: '30 RON',
            category: 'Film',
            image: 'https://example.com/shawshank.jpg',
            lat: 46.7710,
            lng: 23.5950
        },
        // Evenimente pentru 21 Noiembrie 2025
        {
            id: 'evt31',
            title: 'Targ de Artizanat',
            description: 'Produse artizanale traditionale.',
            date: '2025-11-21',
            time: '10:00',
            location: 'Piata Unirii',
            address: 'Piata Unirii, Cluj-Napoca',
            price: 'Intrare libera',
            category: 'Targ',
            image: 'https://example.com/craft_fair.jpg',
            lat: 46.7694,
            lng: 23.5900
        },
        {
            id: 'evt32',
            title: 'Concert Muzica Clasica',
            description: 'Concert de muzica clasica cu simfonii de Mozart.',
            date: '2025-11-21',
            time: '19:30',
            location: 'Filarmonica de Stat',
            address: 'Str. Kogalniceanu 11, Cluj-Napoca',
            price: '70-150 RON',
            category: 'Muzica',
            image: 'https://example.com/classical_concert.jpg',
            lat: 46.7700,
            lng: 23.5980
        },
        {
            id: 'evt33',
            title: 'Tur al Muzeului Etnografic',
            description: 'Tur ghidat prin muzeul etnografic.',
            date: '2025-11-21',
            time: '12:00',
            location: 'Muzeul Etnografic al Transilvaniei',
            address: 'Str. Memorandumului 21, Cluj-Napoca',
            price: '15 RON',
            category: 'Turism',
            image: 'https://example.com/ethnographic_museum.jpg',
            lat: 46.7680,
            lng: 23.5920
        },
        {
            id: 'evt34',
            title: 'Workshop de Fotografie de Portret',
            description: 'Invatati tehnici de fotografie de portret.',
            date: '2025-11-21',
            time: '15:00',
            location: 'Centrul de Fotografie',
            address: 'Str. Horea 30, Cluj-Napoca',
            price: '100 RON',
            category: 'Fotografie',
            image: 'https://example.com/portrait_photography.jpg',
            lat: 46.7675,
            lng: 23.5905
        },
        {
            id: 'evt35',
            title: 'Film: The Godfather',
            description: 'Proiectie speciala a filmului The Godfather.',
            date: '2025-11-21',
            time: '21:00',
            location: 'Cinema Victoria',
            address: 'Piata Unirii, Cluj-Napoca',
            price: '35 RON',
            category: 'Film',
            image: 'https://example.com/godfather.jpg',
            lat: 46.7694,
            lng: 23.5900
        },
        // Evenimente pentru 22 Noiembrie 2025
        {
            id: 'evt36',
            title: 'Gaming Tournament',
            description: 'Turneu de jocuri video cu premii.',
            date: '2025-11-22',
            time: '14:00',
            location: 'Gaming Arena',
            address: 'Str. Bucuresti 45, Cluj-Napoca',
            price: '50 RON',
            category: 'Jocuri',
            image: 'https://example.com/gaming_tournament.jpg',
            lat: 46.7720,
            lng: 23.6000
        },
        {
            id: 'evt37',
            title: 'Tech Conference',
            description: 'Conferinta despre tehnologii noi si inovatii.',
            date: '2025-11-22',
            time: '10:00',
            location: 'Cluj Business Center',
            address: 'Str. Memorandumului 28, Cluj-Napoca',
            price: '100 RON',
            category: 'Tehnic',
            image: 'https://example.com/tech_conference.jpg',
            lat: 46.7685,
            lng: 23.5925
        },
        {
            id: 'evt38',
            title: 'Curs de Programare',
            description: 'Curs introductiv de programare JavaScript.',
            date: '2025-11-22',
            time: '16:00',
            location: 'TechHub',
            address: 'Str. Napoca 12, Cluj-Napoca',
            price: '75 RON',
            category: 'Educatie',
            image: 'https://example.com/programming_course.jpg',
            lat: 46.7700,
            lng: 23.5940
        },
        {
            id: 'evt39',
            title: 'Maraton de Alergat',
            description: 'Maraton de 10km prin oras.',
            date: '2025-11-22',
            time: '08:00',
            location: 'Parcul Central',
            address: 'Str. Horea 1, Cluj-Napoca',
            price: '40 RON',
            category: 'Sport',
            image: 'https://example.com/running_marathon.jpg',
            lat: 46.7715,
            lng: 23.5955
        },
        {
            id: 'evt40',
            title: 'Petrecere Sociala',
            description: 'Petrecere de networking pentru profesionisti.',
            date: '2025-11-22',
            time: '19:00',
            location: 'Centrul de Evenimente',
            address: 'Str. Avram Iancu 20, Cluj-Napoca',
            price: '60 RON',
            category: 'Social',
            image: 'https://example.com/social_party.jpg',
            lat: 46.7705,
            lng: 23.5950
        }
    ]
};

// Exportăm datele
try {
    if (typeof module !== 'undefined' && module.exports) {
        module.exports = eventsData;
    } else {
        // Setăm datele în obiectul global window
        window.events = eventsData;
        
        // Dacă există un eventManager, îi setăm datele
        if (window.eventManager && typeof window.eventManager.setEvents === 'function') {
            window.eventManager.setEvents(eventsData);
        }
    }
} catch (e) {
    console.error('Error exporting events data:', e);
}
